version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5430:5432"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "31167:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
